### ISSUE TITLE
 IGPGTG color space

### ISSUE THREAD

**Issue by nschloe** [nschloe/colorio#106]
https://www.ingentaconnect.com/content/ist/jpi/2020/00000003/00000002/art00002

**Comment by JoostScheffer** [comment]
It currently isn't available anymore.
Luckily there is a wayback archive snapshot: https://web.archive.org/web/20210201173354/https://www.ingentaconnect.com/content/ist/jpi/2020/00000003/00000002/art00002#

Here is the doi of the paper:
[https://doi.org/10.2352/J.Percept.Imaging.2020.3.2.020401](https://web.archive.org/web/20210201173354/https://doi.org/10.2352/J.Percept.Imaging.2020.3.2.020401)

**Comment by nschloe** [comment]
Fixed now.
