### ISSUE TITLE
Oklab normalisation (?)

### ISSUE THREAD

**Issue by dnadlinger** [nschloe/colorio#120]
`okl.from_xyz100(colorio.illuminants.whitepoints_cie1931["D65"])` gives `cbrt(100)` times the expected result.

Indeed, the tests compare `okl.from_xyz100(colorio.illuminants.whitepoints_cie1931["D65"] / 100)` to the expected result of `[1, 0, 0]` instead.

Why the factor 100? Isn't that at odds with the XYZ100 in the function name?

**Comment by nschloe** [comment]
Where do you get your reference value?

**Comment by nschloe** [comment]
Got it, from https://bottosson.github.io/posts/oklab/:

> D65 (normalized with Y=1Y=1) should transform to L=1, a=0, b=0L=1,a=0,b=0 and

**Comment by nschloe** [comment]
Turns out you're right, fixing now.
