### ISSUE TITLE
Is HSV colorspace shifted?

### ISSUE THREAD

**Issue by Davide-sd** [nschloe/colorio#137]
I'm trying to convert HSV to RGB:

```python
import numpy as np
import colorio
cs = colorio.cs.HSV()
h = np.array(0)
s, v = np.ones_like(h), np.ones_like(h)
cs.to_srgb1((h, s, v))

# array([0., 1., 0.])
```

With `h=0` I was expecting `array([1., 0., 0.])`. Thus the title question...

**Comment by nschloe** [comment]
Thanks for the report! This is fixed now. You can also simply
```python
cs.to_srgb1([0.0, 1.0, 1.0])
```
instead of creating arrays etc.
