### ISSUE TITLE
conversion between CAM16USC and sRBG1

### ISSUE THREAD

**Issue by FelicityN** [nschloe/colorio#142]
I want to be able to convert from CAM16-UCS to sRGB1, and sRGB1 to CAM16-UCS. This doesn't look like this is directly supported (unless I am missing something?).

**Comment by nschloe** [comment]
Sure. Every color space has `from_xyz` and `to_xyz`, so you'd first convert from CAM16 to XYZ, then from XYZ to SRGB1.

**Comment by FelicityN** [comment]
I see now, thanks!
