### ISSUE TITLE
Gamut plot with sRGB triangle

### ISSUE THREAD

**Issue by burggraaff** [nschloe/colorio#143]
Hi, I previously used `_tools.plot_flat_gamut` to draw an (x, y) gamut with the monochromatic edge and sRGB triangle indicated. I see the latter feature was removed in commits de3c7fad3d969ecce7ee53a8f935267fb452eec5 and  da26e541e425e555392f9fb06a5d1c2f14d4dcfc. It's not immediately obvious to me why this was removed, and whether it was removed outright or simply refactored. I can see that `plot_xy_gamut` now does everything except the sRGB triangle.

What steps should I take to recreate the sRGB triangle? Is there a different function for this now, which I have missed?

**Comment by nschloe** [comment]
I can't recall entirely but I think there's something like plot_rgb_slice.
