### ISSUE TITLE
Can't get the OKLAB functions to work

### ISSUE THREAD

**Issue by abnormally-distributed** [nschloe/colorio#166]
Not sure what I am doing wrong... Here are the results of a couple things I used in the console. I'm not sure what the "self" arguments it wants should be. 

`colorio.cs.OKLAB.from_xyz100(xyz100 = [[1.0497487, 1.0803128, 0.1222619]])
Traceback (most recent call last):

  File "<ipython-input-19-055fdb079366>", line 1, in <module>
    colorio.cs.OKLAB.from_xyz100(xyz100 = [[1.0497487, 1.0803128, 0.1222619]])

TypeError: from_xyz100() missing 1 required positional argument: 'self'

colorio.cs.OKLAB.from_xyz100(xyz100 = [1.0497487, 1.0803128, 0.1222619])
Traceback (most recent call last):

  File "<ipython-input-20-7d434d9e8b2a>", line 1, in <module>
    colorio.cs.OKLAB.from_xyz100(xyz100 = [1.0497487, 1.0803128, 0.1222619])

TypeError: from_xyz100() missing 1 required positional argument: 'self'`

**Comment by nschloe** [comment]
You need to instantiate the class:
```
cs = colorio.cs.OKLAB()
cs.from_xyz100(...)
```
