### ISSUE TITLE
ColorCoordinates - get_rgb1("clip") replacement.

### ISSUE THREAD

**Issue by matthewfurr** [nschloe/colorio#190]
Hi Nico,

First wanted to say thanks for creating and maintaining colorio. I just came across it and I think it will be extremely useful as I write my thesis on extended gamut (7-color ink sets) color stability compared to the typical 4-color (CMYK) ink sets. I opened up the [create-readme-plots.py](https://github.com/nschloe/colorio/blob/main/create-readme-plots.py) to familiarize myself with some of your tools and I came across a couple of things I'm hoping you can clarify for me.

I'm looking at lines 149-165:

```python
# observer
srgb = colorio.cs.SrgbLinear()
xyz100 = colorio.cs.XYZ100()

cols = [
    ColorCoordinates([30.0, 0.0, 0.0], xyz100).get_rgb1("clip"),
    ColorCoordinates([0.0, 30.0, 0.0], xyz100).get_rgb1("clip"),
    ColorCoordinates([0.0, 0.0, 30.0], xyz100).get_rgb1("clip"),
]
obs = colorio.observers.cie_1931_2()
plt.plot(obs.lmbda_nm, obs.data[0], color=cols[0], label="$\\overline{x}$")
plt.plot(obs.lmbda_nm, obs.data[1], color=cols[1], label="$\\overline{y}$")
plt.plot(obs.lmbda_nm, obs.data[2], color=cols[2], label="$\\overline{z}$")
plt.xlabel("wavelength [nm]")
plt.legend()
plt.savefig("cie-standard-observer-2.svg", transparent=True, bbox_inches="tight")
plt.show()
```

I believe the second line here should be `srgb = colorio.cs.SRGBlinear()` now. It looks like RGB is now capitalized and the L is now lowercase in the `src/colorio/cs/_srgb.py` ([link to _srgb.py](https://github.com/nschloe/colorio/blob/d355e6e0fcacc762ee707fc60f74bf48ba5fd81f/src/colorio/cs/_srgb.py#L17)) Is that a correct assumption?

Now for my question. It looks like `.get_rgb1()` no longer exists in `_color_coordinates.py` ([link to _color_coordinates.py](https://github.com/nschloe/colorio/blob/main/src/colorio/cs/_color_coordinates.py)). What should I be using here instead? If I look at the History of this file it looks like it once existed, but I can't figure out what I should be using instead now.

Thanks in advance!
Matt

**Comment by nschloe** [comment]
Hi Matt,

Thanks for notifying! I'll check it out after dinner.

**Comment by nschloe** [comment]
Fixed now. Check out the readme for more examples!

**Comment by matthewfurr** [comment]
Awesome! I think I understand what is happening here with `.convert(srgb)`
Thanks for the quick response!
