### ISSUE TITLE
Oklab Lightness transform included or not? 

### ISSUE THREAD

**Issue by swamidass** [nschloe/colorio#196]
Oklab was updated with a new lightness scale. See section "Intermission - a new lightness estimate for Oklab": https://bottosson.github.io/posts/colorpicker/

Does colorio use this rescaled version of oklab or not? This is important, because there is some ambguity now in how "oklab" is defined.

**Comment by nschloe** [comment]
Oklab now has the parameter `lightness_type`. Set it to `"Lr"` to get the new CIECAM-like lightness estimate.

**Comment by swamidass** [comment]
Thanks!
