### ISSUE TITLE
dead links, README.md to https://github.com/nschloe/colorio/blob/...

### ISSUE THREAD

**Issue by denis-bz** [nschloe/colorio#199]
Hi Nico
 all the links to src in README.md like XYZ -> https://github.com/nschloe/colorio/blob/main/src/colorio/cs/_xyz.py are dead;
https://github.com/nschloe/colorio has only the README and articles/, no `blob/` ?
cheers

**Comment by nschloe** [comment]
Yes, I'm restructuring the work right now. I've removed the dead links, thanks for the notification!
