### ISSUE TITLE
unable to install colorio

### ISSUE THREAD

**Issue by mekides** [nschloe/colorio#203]
I am getting the following errors when I try to install colorio on windows and ubuntu. 

ERROR: Could not find a version that satisfies the requirement colorio (from versions: none)
ERROR: No matching distribution found for colorio.

Is the project discontinued? Looking forward to your reply.

With many thanks,

**Comment by nschloe** [comment]
Python version?

**Comment by mekides** [comment]
Yes, that was the issue. Mine was 3.6 and I think for colorio we need at least 3.7.  Thank you for the prompt reply.
