### ISSUE TITLE
Colour Difference

### ISSUE THREAD

**Issue by sushilkumarprem** [nschloe/colorio#204]
Hey Nico, first of all, thank you for your work. Secondly, I am a designer who lacks experience with perceptual uniform colour models (although it seems like designers should,  we are rarely trained on colour appearance models). So, please forgive me if this is a stupid question. 

You have mentioned the colour difference formulas for CIE76, CIE94, CIEDE2000 and CMC l:c. [here ](https://pypi.org/project/colorio/#description)but not CAM16-UCS, is there a reason for that? 

Could you tell me how I can find the colour difference for the CAM16-UCS model, and the difference in lightness J′, colourfulness M′ and hue h′?

**Comment by nschloe** [comment]
CAM16-UCS is not a color difference formula, but a color space. It tries to fit color data in a Euclidean space. To get the difference between two colors, just take the Euclidean difference
```python
sqrt(J ** 2 + M ** 2 + h ** 2)
```

**Comment by sushilkumarprem** [comment]
![image](https://user-images.githubusercontent.com/47389154/201556868-401f202b-337f-44e0-ab86-56ebc239d446.png)

Could you please tell me what is the purpose of transformation in step A5? I tried contacting the paper's authors but didn't get any response. 

Do you have a datasheet, I can use to validate my coding?  Two RGB values, their corresponding outputs in CAM16/CAM16-UCS colour space, and their deltaE value?  I would appreciate it very much.
