### ISSUE TITLE
Images missing from README

### ISSUE THREAD

**Issue by jamadagni** [nschloe/colorio#34]
Hello. The README currently has the following line:

> The images below all show the SRGB gamut in the respective color space.

… but there are no images below this. Please add the images. (Are they the same under the `gh-pages` branch?)

**Comment by nschloe** [comment]
> Are they the same under the gh-pages branch?

Yup.

**Comment by nschloe** [comment]
>  Please add the images. 

I'd say just find the images in the gh-pages branch or recreate them yourself. It's easy enough to do it. No need for all of them to be in the README.

**Comment by jamadagni** [comment]
OK fine but change the README accordingly then.

**Comment by jamadagni** [comment]
Huh you could have mentioned that this was closed by PR #35. OK thanks.
