### ISSUE TITLE
meshio output problems

### ISSUE THREAD

**Issue by jamadagni** [nschloe/colorio#36]
The README says:

    The data can be written in all formats supported by
    [meshio](https://github.com/nschloe/meshio).

However, since [it is not clear that all formats are immediately supported by just doing `pip install colorio`](https://github.com/nschloe/meshio/issues/264#issuecomment-482495846), I did some further testing:

    #! /usr/bin/env python3

    from meshio.helpers import _extension_to_filetype
    extensions = tuple(_extension_to_filetype.keys())
    dependenciesForExtensions = {}
    extensionsWithOtherProblems = {}
    extensionsWithoutProblems = []

    import colorio
    cielab = colorio.CIELAB()

    for ext in extensions:
        try:
            colorio.show_srgb_gamut(cielab, "out" + ext)
        except ModuleNotFoundError as e:
            moduleName = str(e).split("'")[1]
            if moduleName not in dependenciesForExtensions:
                dependenciesForExtensions[moduleName] = []
            dependenciesForExtensions[moduleName].append(ext)
        except Exception as e:
            extensionsWithOtherProblems[ext] = str(e)
        else:
            extensionsWithoutProblems.append(ext)

    print("\nExtensions without problems:\n{}".format(extensionsWithoutProblems))
    print("\nExtensions with dependency problems:\n{}̣".format(dependenciesForExtensions))
    print("\nExtensions with other problems:\n{}".format(extensionsWithOtherProblems))

and got the output:

    WARNING:root:Writing MSH4.1 unimplemented, falling back on MSH2
    WARNING:root:Binary Gmsh needs 32-bit integers (got int64). Converting.
    WARNING:root:Dolfin's XML is a legacy format. Consider using XDMF instead.

    Extensions without problems:
    ['.mesh', '.msh', '.post', '.post.gz', '.dato', '.dato.gz', '.vtk', '.inp']

    Extensions with dependency problems:
    {'netCDF4': ['.e', '.ex2', '.exo'], 'h5py': ['.med', '.h5m'], 'lxml': ['.xml', '.vtu', '.xdmf', '.xmf', '.svg']}̣

    Extensions with other problems:
    {'.off': 'Can only deal with triangular faces', '.stl': 'STL can only write triangle cells.', '.mdpa': 'must be str, not bytes'}

Even after installing the extra module dependencies, trying to use SVG for output format produces the error `SVG can only handle flat 2D meshes (shape: (125000, 3))`

Thus the above statement in the README requires change. Specifically it would seem that:

1. the `.off`, `.stl`, `.mdpa` and `.svg` formats aren't feasible for use with **colorio** (but I may be wrong), and:
2. some formats require certain dependencies which aren't pulled in by `pip install colorio`

So I suggest the following replacement wording:

    The data can be written in most formats supported by
    [meshio](https://github.com/nschloe/meshio) (with the exception of `.off`,
    `.stl`, `.mdpa` and `.svg`). However, some formats may require packages
    such as LXML to be installed in addition.

**Comment by nschloe** [comment]
I've updated the readme in #37.
