### ISSUE TITLE
Add support for the Munsell Color System

### ISSUE THREAD

**Issue by jamadagni** [nschloe/colorio#39]
Hello. Currently Colorio has support for a large number of colour systems, however support for the Munsell system is missing. To find how to do this I googled for “srgb to munsell” and arrived at the following links which may be useful:

1. https://github.com/privet-kitty/dufy is a LISP library providing support for this. 
2. http://ncss-tech.github.io/aqp/docs/reference/munsell2rgb.html
3. http://pteromys.melonisland.net/munsell/

Thanks!

**Comment by jrus** [comment]
Munsell color system is a lookup table. There is no formula involved, just a specific set of points in Munsell space with designated XYZ coordinates.

There are a variety of possible ways someone might choose to interpolate those data, but no obvious single right method, and different interpolation schemes will lead to slightly different results.

**Comment by nschloe** [comment]
@jrus is right. What you can do is look at the Munsell data points in the various color spaces with, e.g.,
```
import colorio
colorio.show_munsell(colorio.CIELUV() V=5)
```

**Comment by jamadagni** [comment]
Point taken, but how can I actually get (as opposed to seeing in a graph)
the values in a color space corresponding to the Munsell points?

**Comment by nschloe** [comment]
I can add this.

**Comment by nschloe** [comment]
There now is `colorio.get_munsell_data()`.
