### ISSUE TITLE
OSA for black returns NaNs

### ISSUE THREAD

**Issue by genmeblog** [nschloe/colorio#63]
Playing with OSA colorspace (porting to Clojure) and found that for black OSA colorio returns NaNs

```
>>> rgb.from_xyz100(osa.to_xyz100(osa.from_xyz100(rgb.to_xyz100([0,0,0]))))
array([nan, nan, nan])
```

This is caused by this division https://github.com/nschloe/colorio/blob/master/colorio/_osa.py#L38

**Comment by genmeblog** [comment]
Also I'm getting some extreme values for one specific case:

```
>>> osa.from_xyz100(rgb.to_xyz100([2.0/255.0,0,2.0/255.0]))
array([ -10.72384881, 2770.45300697, 2112.87808767])
```

**Comment by nschloe** [comment]
Thanks for the report. The [0, 0, 0] issue is now fixed. For SRGB, don't forget to undo the gamma correction:
```python
import colorio

osa = colorio.OsaUcs()
rgb = colorio.SrgbLinear()

linear = rgb.from_srgb1([2.0 / 255.0, 0, 2.0 / 255.0])
out = osa.from_xyz100(rgb.to_xyz100(linear))
print(out)
```

**Comment by genmeblog** [comment]
Yes, I know about gamma correction. Here is example for sRGB.

```
>>> linear = rgb.from_srgb1([18.0 / 255.0, 7.0 / 255.0, 4.0 / 255.0])
>>> out = osa.from_xyz100(rgb.to_xyz100(linear))
>>> out
array([-1.07244887e+01,  6.91987732e+04, -5.70147998e+04])
```

**Comment by nschloe** [comment]
I get
```python
import colorio

osa = colorio.OsaUcs()
rgb = colorio.SrgbLinear()

print(osa.from_xyz100(rgb.to_xyz100(rgb.from_srgb256([18, 7, 4]))))
print(osa.from_xyz100(rgb.to_xyz100(rgb.from_srgb256([18, 2, 22]))))
print(osa.from_xyz100(rgb.to_xyz100(rgb.from_srgb256([0, 1, 43]))))
```
```
[ -10.728835   -131.66432085  108.60641022]
[ -10.72889419 -291.28894879 -297.99369533]
[ -10.73115815  112.07368631 -464.89918723]
```

**Comment by genmeblog** [comment]
Ok. Just curious: why you divide by 256.0 instead of 255.0?
Anyway, there are areas where these values goes to some extreme numbers. Possibly that's ok since reverse conversion gives originals.

**Comment by nschloe** [comment]
> Ok. Just curious: why you divide by 256.0 instead of 255.0?

An oversight, fixed now. Thanks!

> Anyway, there are areas where these values goes to some extreme numbers. Possibly that's ok since reverse conversion gives originals.

Yep, that's just OSA-UCS.
