### ISSUE TITLE
Divide-by-zero & NaN in RGB to HSL/HSV conversion

### ISSUE THREAD

**Issue by toaarnio** [nschloe/colorio#75]
```
>>> import colorio
>>> hsl = colorio.HSL().from_srgb1([1, 1, 1])
/home/user/.local/lib/python3.6/site-packages/colorio/_hsl.py:21: RuntimeWarning: invalid value encountered in true_divide
  H[i] = 60 * (0 + (srgb[1][i] - srgb[2][i]) / diff[i])
>>> hsl
array([nan, 0., 1.0])
```

Is this a feature or a bug? It's true that hue is undefined if R=G=B, so returning NaN kind of makes sense. On the other hand, if this is an intentional choice, the warning should be suppressed.

**Comment by nschloe** [comment]
`NaN` is intended and makes sense, as you noted. It probably best if you suppress the warning yourself with
```python
import numpy as np
np.seterr(divide='ignore', invalid='ignore')
```

**Comment by toaarnio** [comment]
Right - that's what I'm currently doing, but it has the unintended consequence that legitimate warnings may get suppressed as well.

**Comment by nschloe** [comment]
You could just enable it again after the call?

**Comment by toaarnio** [comment]
Sure:
```
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=RuntimeWarning)
    hsl = colorio.HSL().from_srgb1(rgb)
    hsl = np.nan_to_num(hsl)
```

Still, there's a chance that another (possibly legitimate) RuntimeWarning from colorio gets suppressed and therefore unnoticed.

**Comment by nschloe** [comment]
I wouldn't worry about this now.
