### ISSUE TITLE
V0.6.5 has AttributeError: 'OKLAB' object has no attribute 'k0'

### ISSUE THREAD

**Issue by fredsavoir** [nschloe/colorio#85]
Hi,

If you do a simple:

import colorio
colorspace = colorio.OKLAB()
colorspace.show_ebner_fairchild()

you will get an error:
AttributeError: 'OKLAB' object has no attribute 'k0'

Hope it's help.
Fred

**Comment by nschloe** [comment]
Fixed in master.
