### ISSUE TITLE
Still issue #85

### ISSUE THREAD

**Issue by fredsavoir** [nschloe/colorio#87]
Hi again,

here python3 -m pip install https://github.com/nschloe/colorio/archive/master.zip
Building wheels for collected packages: colorio
  Building wheel for colorio (PEP 517) ... done
  Created wheel for colorio: filename=colorio-0.6.5-py3-none-any.whl size=136229 sha256=8c36713987a67955aaedc440cfa2ec585745eaaa9898d7ba080ac8de24ba0286
  Stored in directory: /private/var/folders/nm/2psc68vd333ffgf21xp05t_40000gn/T/pip-ephem-wheel-cache-q05mo9m2/wheels/ad/9a/3b/ac10b724f443945bae92086cb643df4fa29d7cac7b4dd3ad38
Successfully built colorio
Installing collected packages: colorio
Successfully installed colorio-0.6.5

then simply try:
>>> import colorio
>>> colorspace = colorio.OKLAB()
>>> colorspace.show_ebner_fairchild()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/colorio/_color_space.py", line 467, in show_ebner_fairchild
    self.plot_ebner_fairchild()
  File "/usr/local/lib/python3.9/site-packages/colorio/_color_space.py", line 489, in plot_ebner_fairchild
    _plot_color_constancy_data(d, wp, self)
  File "/usr/local/lib/python3.9/site-packages/colorio/_color_space.py", line 605, in _plot_color_constancy_data
    k0 = colorspace.k0
AttributeError: 'OKLAB' object has no attribute 'k0'

**Comment by fredsavoir** [comment]
or python3 -m pip install https://github.com/nschloe/colorio/archive/master.zip --no-binary :all:
Collecting https://github.com/nschloe/colorio/archive/master.zip
  Using cached https://github.com/nschloe/colorio/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (1.19.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (3.3.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (5.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (8.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (0.10.0)
Requirement already satisfied: six in /usr/local/Cellar/protobuf/3.14.0/libexec/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->colorio==0.6.5) (1.15.0)
Building wheels for collected packages: colorio
  Building wheel for colorio (PEP 517) ... done
  Created wheel for colorio: filename=colorio-0.6.5-py3-none-any.whl size=136229 sha256=5dbe0f6e924021ceba5a024f19c461aaef9b8083b25b2627b2555e0415a44e46
  Stored in directory: /private/var/folders/nm/2psc68vd333ffgf21xp05t_40000gn/T/pip-ephem-wheel-cache-3zjy1dz4/wheels/ad/9a/3b/ac10b724f443945bae92086cb643df4fa29d7cac7b4dd3ad38
Successfully built colorio
Installing collected packages: colorio
Successfully installed colorio-0.6.5

Same error. Did I miss something ?

thanks

fred

**Comment by fredsavoir** [comment]
python3 -m pip install git+https://github.com/nschloe/colorio.git --no-binary :all:
Collecting git+https://github.com/nschloe/colorio.git
  Cloning https://github.com/nschloe/colorio.git to /private/var/folders/nm/2psc68vd333ffgf21xp05t_40000gn/T/pip-req-build-6trzn9qv
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (1.19.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (5.3.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/site-packages (from colorio==0.6.5) (3.3.3)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (8.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.9/site-packages (from matplotlib->colorio==0.6.5) (2.4.7)
Requirement already satisfied: six in /usr/local/Cellar/protobuf/3.14.0/libexec/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->colorio==0.6.5) (1.15.0)
Building wheels for collected packages: colorio
  Building wheel for colorio (PEP 517) ... done
  Created wheel for colorio: filename=colorio-0.6.5-py3-none-any.whl size=136229 sha256=142e2d3e14257c4cfa94c5542934fd367009109db38a0b88533f62ad86c21a55
  Stored in directory: /private/var/folders/nm/2psc68vd333ffgf21xp05t_40000gn/T/pip-ephem-wheel-cache-bpw3ktht/wheels/b6/79/69/bdfceaf8a4a8d1dfd646ca174c1598cedea96b73f49a81fc1a
Successfully built colorio
Installing collected packages: colorio
Successfully installed colorio-0.6.5


same here....

**Comment by nschloe** [comment]
Right, haven't pushed to master yet. Will do one of these days.

**Comment by fredsavoir** [comment]
Thanks a lot
