### ISSUE TITLE
Luo-Rigg data no longer missing

### ISSUE THREAD

**Issue by svgeesus** [nschloe/colorio#88]
The Data Readme states, under missing data,

> M.R. Luo and B. Rigg, Chromaticity-discrimination ellipses for surface colours, Color Res. Appl. 11(1), 25-42 (1986).

bu there is a Luo-Rigg folder with that data. Or is this another dataset from the same paper?

**Comment by nschloe** [comment]
The data is there from the Luo-Rigg paper itself (a copy-paste from one of their printed tables), but they get their ellipses from other sources, e.g., [BFD](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1478-4408.1982.tb03602.x) (2776 pairs of samples). That's what's not in there.

By the way, if you're only after the raw data, have a look at https://github.com/nschloe/color-data.
